// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMTHs-tX7Vsdn9GGIVxk0w6_kJ0Kr5-sw',
    appId: '1:489839752903:web:84545669f4c50748b2b0e2',
    messagingSenderId: '489839752903',
    projectId: 'pindrive-ghana',
    authDomain: 'pindrive-ghana.firebaseapp.com',
    storageBucket: 'pindrive-ghana.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-StghZ-NMkpePQNu6Ioh3LQK2-TvC4v4',
    appId: '1:489839752903:android:c2555d89a0d9acbdb2b0e2',
    messagingSenderId: '489839752903',
    projectId: 'pindrive-ghana',
    storageBucket: 'pindrive-ghana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HMSHspoIT67JceWCbLoDMI-iSnpgcsc',
    appId: '1:489839752903:ios:3e7a3460722671fdb2b0e2',
    messagingSenderId: '489839752903',
    projectId: 'pindrive-ghana',
    storageBucket: 'pindrive-ghana.firebasestorage.app',
    iosBundleId: 'com.example.pindrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5HMSHspoIT67JceWCbLoDMI-iSnpgcsc',
    appId: '1:489839752903:ios:3e7a3460722671fdb2b0e2',
    messagingSenderId: '489839752903',
    projectId: 'pindrive-ghana',
    storageBucket: 'pindrive-ghana.firebasestorage.app',
    iosBundleId: 'com.example.pindrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMTHs-tX7Vsdn9GGIVxk0w6_kJ0Kr5-sw',
    appId: '1:489839752903:web:947b1cfcfbb21c2cb2b0e2',
    messagingSenderId: '489839752903',
    projectId: 'pindrive-ghana',
    authDomain: 'pindrive-ghana.firebaseapp.com',
    storageBucket: 'pindrive-ghana.firebasestorage.app',
  );
}
